from pathlib import Path, PurePath

root = PurePath(Path('.').absolute())

Import('gcc_env')
env = gcc_env

sources = Glob("*.c")

build = str(env['BUILD'] / root.relative_to(env['SRC']))

o_list = []
for source in sources:
    name = source.name
    name = name.split('.')[0]
    o_list.append(f'{build}/{name}')
    env.Object(f'{build}/{name}', source)

env.Ld(f'{build}/kernel', o_list)
env.Objcopy(f'{build}/kernel')
