from pathlib import Path, PurePath

root = PurePath(Path('.').absolute())

Import('nasm_env')
env = nasm_env

build = str(env['BUILD'] / root.relative_to(env['SRC']))

env.Object(f'{build}\\boot', ['mbr.asm'])
