from pathlib import Path, PurePath

root = PurePath(Path('.').absolute())

Import('env')
env = env

build = str(env['BUILD'] / root.relative_to(env['SRC']))

sources = Glob("*\\*\\*.c")

o_list = []
for source in sources:
    name = str(source).split('.')[0]
    o_list.append(f'{build}\\{name}')
    env.Object(f'{build}\\{name}', source)

env.Ld(f'{build}\\libs.obj', o_list)
