from pathlib import Path, PurePath

root = PurePath(Path('.').absolute())

Import('gcc_env')
env = gcc_env

build = str(env['BUILD'] / root.relative_to(env['SRC']))

SConscript(dirs=[f'boot\\{env["ARCH"]}', 'kernel'])
# env.Copy(f'{build}\\MSC', [f'{build}\\boot\\x86\\boot.bin', f'{build}\\kernel\\kernel.bin'])
env.Copy(f'{build}\\MSC', [f'{build}\\kernel\\kernel.bin'])
