from pathlib import Path, PurePath

root = PurePath(Path('.').absolute())

Import('gcc_env')
env = gcc_env

build = str(env['BUILD'] / root.relative_to(env['SRC']))

SConscript(dirs=[f'boot/{env["ARCH"]}','kernel'])
